stages:
- build
- test

build:ubuntu:gnu_debug_openmp:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake
      -DCMAKE_BUILD_TYPE=Debug
      -DKOKKOS_DIR=/opt/sw/Kokkos/BuildOpenMP_9afaa87
      -DSILO_DIR=/opt/sw/silo/4.10.2
      ../src
  - make
  tags:
  - ubuntu
  artifacts:
    expire_in: 4 hrs
    paths:
    - build

test:ubuntu:gnu_debug_openmp:
  stage: test
  script:
  - cd build
  - ctest -V
  tags:
  - ubuntu
  dependencies:
  - build:ubuntu:gnu_debug_openmp

build:ubuntu:cuda_debug:
  stage: build
  script:
  - module use /usr/local/modules
  - module load cuda
  - mkdir build
  - cd build
  - cmake
      -DGRIT_USE_CUDA:BOOL=ON
      -DCMAKE_BUILD_TYPE=Debug
      -DKOKKOS_DIR=/opt/sw/Kokkos/BuildCuda8.0_9afaa87
      -DCMAKE_CXX_FLAGS="-expt-extended-lambda"
      -DSILO_DIR=/opt/sw/silo/4.10.2
      ../src
  - make
  tags:
  - ubuntu
  artifacts:
    expire_in: 4 hrs
    paths:
    - build

test:ubuntu:cuda_debug:
  stage: test
  script:
  - cd build
  - ctest -V
  tags:
  - ubuntu
  dependencies:
  - build:ubuntu:cuda_debug
